apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
  labels:
    app: nestjs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-api
  template:
    metadata:
      labels:
        app: nestjs-api
    spec:
      containers:
        - name: bnb-api
          # image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:${IMAGE_TAG}
          image: docker.io/orafaribeiro/bnb-api:895642f806b4a677b499ab1c7498d5ccf8892f42
          resources:
            limits:
              cpu: "0.5"
              memory: 100Mi
          ports:
            - containerPort: 3000
