apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
  labels:
    app: nestjs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-api
  template:
    metadata:
      labels:
        app: nestjs-api
    spec:
      containers:
        - name: bnb-api
          image: DOCKER_REGISTRY/DOCKER_USERNAME/DOCKER_REPOSITORY:IMAGE_TAG
          resources:
            limits:
              cpu: "0.5"
              memory: 100Mi
          ports:
            - containerPort: 3000
