version: '3.8'
services:
  database:
    image: mysql
    container_name: my-database
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 8000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 87654321
      MYSQL_DATABASE: db-docker
      MYSQL_USER: bnb-user
      MYSQL_PASSWORD: Admin1234